apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.fullname" . }}-config
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := deepCopy .Values.litellm.config }}
    {{- if $config.litellm_settings }}
    {{- if and $config.litellm_settings.cache $config.litellm_settings.cache_params }}
    {{- if eq $config.litellm_settings.cache_params.type "redis" }}
    {{- $_ := set $config.litellm_settings.cache_params "host" (printf "%s-redis-master" (include "litellm.fullname" .)) }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- toYaml $config | nindent 4 }}

