{{- $llamastack := index .Values "llama-stack" }}
{{- if and $llamastack $llamastack.route $llamastack.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
    app.kubernetes.io/component: llamastack
spec:
  {{- with $llamastack.route.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: llamastack
    weight: 100
  port:
    targetPort: http
  {{- if $llamastack.route.tls }}
  tls:
    termination: {{ $llamastack.route.tls.termination }}
    {{- with $llamastack.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ . }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
